name: Test
on:
  push:
jobs:
  full:
    runs-on: ubuntu-latest
    name: OS ubuntu-latest Node.js 18
    steps:
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run unit tests
        run: yarn unit
        env:
          FORCE_COLOR: 2